def class_names():
    '''Function to get the class names'''
    return ['Apple Apple scab',
            'Apple Black rot',
            'Apple Cedar apple rust',
            'Apple healthy',
            'Cherry (including sour) Powdery mildew',
            'Cherry (including sour) healthy',
            'Corn (maize) Cercospora leaf spot Gray leaf spot',
            'Corn (maize) Common rust',
            'Corn (maize) Northern Leaf Blight',
            'Corn (maize) healthy',
            'Grape Black rot',
            'Grape Esca (Black Measles)',
            'Grape Leaf blight (Isariopsis Leaf Spot)',
            'Grape healthy',
            'Orange Haunglongbing (Citrus greening)',
            'Peach Bacterial spot',
            'Peach healthy',
            'Pepper bell Bacterial spot',
            'Pepper bell healthy',
            'Potato Early blight',
            'Potato Late blight',
            'Potato healthy',
            'Squash Powdery mildew',
            'Strawberry Leaf scorch',
            'Strawberry healthy',
            'Tomato Bacterial spot',
            'Tomato Early blight',
            'Tomato Late blight',
            'Tomato Leaf Mold',
            'Tomato Septoria leaf spot',
            'Tomato Spider mites Two-spotted spider mite',
            'Tomato Target Spot',
            'Tomato Tomato Yellow Leaf Curl Virus',
            'Tomato Tomato mosaic virus',
            'Tomato healthy',
            'cotton Aphids',
            'cotton Army worm',
            'cotton Bacterial Blight',
            'cotton Healthy',
            'cotton Powdery Mildew',
            'cotton Target spot']
